Issue 834
rubenlagus/TelegramBots pull request #1011
Opened 2021-12-09 23:45 UTC by nubdub

Add constant DEFAULT to AbilityExtension.java and getter method

2021-12-10 08:36 UTC, Chase22 commented
This should be a public static final without a getter

2022-06-15 00:30 UTC, addo47 requested changes

2022-06-15 00:30 UTC, addo47 commented on telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/util/AbilityExtension.java
> +
I don't like the idea that there's two declarations to this variable (here + in base). We can switch up the DEFAULT variable to become public. I don't see a problem in widening that.

2022-06-15 00:34 UTC, addo47 commented on telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/util/AbilityExtension.java
> +
On a second thought, we can keep this here and remove the one in base ability bot. That class already extends AbilityExtension and people who're implementing the default outside the bot's class will benefit from this localization.

Also, ye this is definitely a static variable with a static method.

2024-01-21 11:48 UTC, closed without merging