Remove function isOkFor to fix #960
rubenlagus/TelegramBots pull request #1071
Opened 2022-05-21 15:31 UTC by montpelllier

Remove function isOkFor so the bot can take action normally on replies with document. The bug has been fixed in Java 9 according to [here](https://bugs.openjdk.java.net/browse/JDK-8044546), so the function may be useless.

2022-05-21 15:36 UTC, montpelllier commented
fix #960

2022-06-15 00:19 UTC, addo47 requested changes

2022-06-15 00:19 UTC, addo47 commented on telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/BaseAbilityBot.java
> -                .filter(reply -> runSilently(() -> reply.isOkFor(update), reply.name()))
The title of this PR is misleading. You are indeed removing the function which is no longer required, but you're changing the behavior of this pipeline.

The reply must be checked, its flags (Predicates of type Predicate<Boolean>) pass.

2022-06-15 00:19 UTC, addo47 commented on telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/objects/Reply.java
> -    return conditions.stream().reduce(true, stateAnd, Boolean::logicalAnd);
Line 57 to be removed, then inline on 58.

2024-01-21 11:48 UTC, closed without merging