Feature/lazy load abilities
rubenlagus/TelegramBots pull request #812
Opened 2020-10-03 23:19 UTC by christianblos

Currently it is not possible to pass dependencies from the bot to an AbilityExtension. Let's take this simple example:

```
public class MyBot extends AbilityBot {
    private final MyConfig config;

    public MyBot(MyConfig config) {
        super("token", "username");
        this.config = config;
    }

    public AbilityExtension createSomeExtension() {
        return new SomeExtension(config);
    }

    @Override
    public int creatorId() {
        return 0;
    }
}
```

Accessing the config object in createSomeExtension() throws a NullPointerException, because abilities are being loaded in the constructor of the AbilityBot. `this.config = config;` was not yet executed, so this.config is null at this point.

In this pull request the abilities are not loaded in the constructor anymore. They are loaded lazily when asking for the abilities the first time. First, I thought about introducing an `initialize()` method, but this would break backward compatibility. So, I decided to go with the lazy loading approach. What are your thoughts?

2020-10-04 00:22 UTC, addo37 commented
Changes look good to me. It might make sense to perhaps rely on a factory to create the bot and initialize afterwards. However, this means we're okay in saying "here's one approach to creating the bot that wouldn't initialize your abilities properly, and here's another that does".

Perhaps, we could @deprecated the constructors and mirror them into factory methods. Thoughts?

2020-10-04 19:30 UTC, christianblos commented
Since the bot is always a custom class implemented by the user of this library, I think a factory is not really possible 🤔 
The params passed to the constructor are still mandatory for the AbilityBot to work, so I personally wouldn't deprecate it. Just registering the abilities must happen at a later point.

If you're fine with breaking backward compatibility, I could also introduce an `onRegister()` method which is called when the bot gets registered (in `TelegramBotsApi.registerBot()`).

```
public void onRegister() {
    registerAbilities();
    initStats();
}
```

2020-10-05 07:55 UTC, addo37 commented
Thinking back, that was quite the terrible suggestion. Thanks for pointing out the caveat.

The onRegister method sounds great. I think, it could be made so that WebhookBot and LongPollingBot interface both inherit from another parent interface (Bot/TelegramBot) with the shared methods declared. The parent interface could have getBotUsername, getBotToken, and onRegister.

This change would be transparent to the user tho. People who'd be interested in doing more stuff on registration would simply override, call super method then carry on.

2020-10-05 15:25 UTC, christianblos commented
Alright, I reverted my old changes and implemented the onRegister method and the main TelegramBot interface.

2020-10-08 06:36 UTC, addo37 requested changes
Please modify the wiki (Bot Testing) to reflect these changes.

2020-10-08 13:06 UTC, christianblos commented on telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/AbilityBot.java
> +    }
🤔 I don't know why I added this. I will remove it again

2020-10-08 13:36 UTC, christianblos commented
I also added a section for overriding the `onRegister()` method to the wiki

2020-10-21 18:42 UTC, rubenlagus commented
Please apply it on dev branch

2020-10-21 21:11 UTC, christianblos commented
Target is now the dev branch

2020-10-22 23:25 UTC, merged