check that username or token are not null or empty
rubenlagus/TelegramBots pull request #851
Opened 2021-01-02 08:20 UTC by centralhardware

to prevent can't remove/delete webhook when token or username are not present

https://github.com/rubenlagus/TelegramBots/issues/850

2021-01-02 11:12 UTC, Chase22 requested changes

2021-01-02 11:12 UTC, Chase22 commented on telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/TelegramBotsApi.java
> +        return bot.getBotUsername().isEmpty()   ||
This is going to cause a NullPointerException if the username is null

2021-01-02 11:12 UTC, Chase22 commented on telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/TelegramBotsApi.java
> +                bot.getBotToken().isEmpty()     ||
Same here

2021-01-28 11:13 UTC, Chase22 approved these changes

2021-03-07 03:23 UTC, rubenlagus commented
Merged separatelly via manual commit

2021-03-07 03:23 UTC, closed without merging